version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  build:
    executor:
      name: node/default
      tag: '22.22.1'
      resource_class: large
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          with-cache: true
      - run:
          name: Build library and demo app
          command: npm run build:lib && npm run build:app
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - node_modules

  test:
    executor:
      name: node/default
      tag: '22.22.1'
      resource_class: large
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          with-cache: true
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Run tests
          command: npm test

  publish:
    executor:
      name: node/default
      tag: '22.22.1'
      resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with NPM registry
          command: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: Publish to NPM
          command: npm publish dist/libs/react-mosaic-component/

workflows:
  version: 2.1
  build-test-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - test:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
